// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv5m_nYflnBqJ_qmeBhqt0r-h11BOizdc',
    appId: '1:946596256869:web:73040e09c1d0a33eddba8c',
    messagingSenderId: '946596256869',
    projectId: 'rachit-dandriyal',
    authDomain: 'rachit-dandriyal.firebaseapp.com',
    storageBucket: 'rachit-dandriyal.appspot.com',
    measurementId: 'G-6DRCLK27JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlV9U7YV2UqNvXSXQRHQJxW2lky4o6mMc',
    appId: '1:946596256869:android:1955cc7a87ae0f16ddba8c',
    messagingSenderId: '946596256869',
    projectId: 'rachit-dandriyal',
    storageBucket: 'rachit-dandriyal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4tpGm9EG6KcNK1BNBgKU-UkV8qD106sI',
    appId: '1:946596256869:ios:e91ebdcae1d585a6ddba8c',
    messagingSenderId: '946596256869',
    projectId: 'rachit-dandriyal',
    storageBucket: 'rachit-dandriyal.appspot.com',
    iosBundleId: 'com.example.rachitDandriyal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4tpGm9EG6KcNK1BNBgKU-UkV8qD106sI',
    appId: '1:946596256869:ios:e91ebdcae1d585a6ddba8c',
    messagingSenderId: '946596256869',
    projectId: 'rachit-dandriyal',
    storageBucket: 'rachit-dandriyal.appspot.com',
    iosBundleId: 'com.example.rachitDandriyal',
  );

}